services:
  frontend:
    build: ./frontend
    container_name: ${COMPOSE_PROJECT_NAME:-newsletter}-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: ${COMPOSE_PROJECT_NAME:-newsletter}-backend
    command: gunicorn app.wsgi:application --bind 0.0.0.0:9000
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT:-9000}:9000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: ${COMPOSE_PROJECT_NAME:-newsletter}-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-django}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-django}
      POSTGRES_DB: ${POSTGRES_DB:-newsletter}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"

volumes:
  postgres_data:
