services:
  frontend:
    build: ./frontend
    container_name: newsletter-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: newsletter-backend
    command: gunicorn app.wsgi:application --bind 0.0.0.0:9000
    volumes:
      - ./backend:/app
    ports:
      - "9000:9000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: newsletter-db
    restart: always
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: newsletter
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
