# Generated by Django 5.2.6 on 2025-09-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='analysis_contexts',
            field=models.JSONField(blank=True, null=True, verbose_name='Contextos Identificados'),
        ),
        migrations.AddField(
            model_name='news',
            name='analysis_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Timestamp da Análise'),
        ),
        migrations.AddField(
            model_name='news',
            name='entities_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Dados de Entidades'),
        ),
        migrations.AddField(
            model_name='news',
            name='sentiment_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Confiança do Sentimento'),
        ),
        migrations.AddField(
            model_name='news',
            name='sentiment_label',
            field=models.CharField(blank=True, max_length=20, verbose_name='Label de Sentimento'),
        ),
        migrations.AddField(
            model_name='news',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Score de Sentimento'),
        ),
    ]
