# Generated by Django 4.2.7 on 2024-01-01 00:00

from django.db import migrations


def add_main_categories(apps, schema_editor):
    """Adiciona as 10 principais categorias de notícias"""
    Category = apps.get_model('common', 'Category')
    
    categories = [
        {'name': 'Política', 'slug': 'politica', 'description': 'Notícias sobre política nacional e internacional'},
        {'name': 'Economia', 'slug': 'economia', 'description': 'Notícias sobre economia, mercado financeiro e negócios'},
        {'name': 'Tecnologia', 'slug': 'tecnologia', 'description': 'Notícias sobre tecnologia, inovação e ciência'},
        {'name': 'Esportes', 'slug': 'esportes', 'description': 'Notícias sobre esportes nacionais e internacionais'},
        {'name': 'Saúde', 'slug': 'saude', 'description': 'Notícias sobre saúde, medicina e bem-estar'},
        {'name': 'Educação', 'slug': 'educacao', 'description': 'Notícias sobre educação e ensino'},
        {'name': 'Meio Ambiente', 'slug': 'meio-ambiente', 'description': 'Notícias sobre meio ambiente e sustentabilidade'},
        {'name': 'Cultura', 'slug': 'cultura', 'description': 'Notícias sobre cultura, arte e entretenimento'},
        {'name': 'Segurança', 'slug': 'seguranca', 'description': 'Notícias sobre segurança pública e criminalidade'},
        {'name': 'Internacional', 'slug': 'internacional', 'description': 'Notícias internacionais e relações exteriores'},
    ]
    
    for category_data in categories:
        Category.objects.create(**category_data)


def reverse_add_main_categories(apps, schema_editor):
    """Remove as categorias principais adicionadas"""
    Category = apps.get_model('common', 'Category')
    
    category_names = [
        'Política', 'Economia', 'Tecnologia', 'Esportes', 'Saúde',
        'Educação', 'Meio Ambiente', 'Cultura', 'Segurança', 'Internacional'
    ]
    
    Category.objects.filter(name__in=category_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_add_analysis_fields'),
    ]

    operations = [
        migrations.RunPython(add_main_categories, reverse_add_main_categories),
    ]
